version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: age-predictor-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: age-predictor-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
