name: Deploy to DigitalOcean

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to deploy (default is latest from main)"
        required: false
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so we can checkout any commit
          ref: "main" # Always start with main

      - name: Checkout specific commit if provided
        if: github.event.inputs.commit_sha != ''
        run: |
          git checkout ${{ github.event.inputs.commit_sha }}

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull specific commit
            cd /opt/age-predictor
            rm -rf repo || true
            git clone https://github.com/${{ github.repository }}.git repo
            cd repo

            # If a specific commit was provided, checkout that commit
            if [ ! -z "${{ github.event.inputs.commit_sha }}" ]; then
              git checkout ${{ github.event.inputs.commit_sha }}
            fi

            cd app

            # Create/update .env file with secrets
            cat > .env << EOL
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            # Add any other environment variables as needed
            EOL

            # Deploy with Docker Compose
            docker-compose down || true
            docker-compose up -d --build

            # Clean up old images (optional)
            docker image prune -f
